# Отключенные правила
disabled_rules:
  - trailing_whitespace

# Включенные дополнительные правила
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Исключить из проверки
excluded:
  - Pods
  - DerivedData
  - .build
  - MoneyFlow/Common/Generated  # SwiftGen файлы

# Длина строки
line_length:
  warning: 120
  error: 200
  ignores_comments: true

# Длина файла
file_length:
  warning: 500
  error: 1000

# Длина функции
function_body_length:
  warning: 50
  error: 100

# Вложенность
nesting:
  type_level: 2

# Имена переменных
identifier_name:
  min_length: 1
  max_length: 50
  excluded:
    - id
    - db
    - url
